### ISSUE TITLE
21BCAD15- CHIRAG KUMAR

### ISSUE THREAD

**Issue by DIVYANUNU** [DIVYANUNU/IVBCAD#14]
1. export HOST_IP={your_real_host_ip} -----    tRYING TO GET IP ADDRES USING THIS COMMAND

( at java.io.PrintStream.write(PrintStream.java:480)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
        at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
        at java.io.PrintStream.write(PrintStream.java:527)
        at java.io.PrintStream.print(PrintStream.java:669)
        at java.io.PrintStream.println(PrintStream.java:806)

3. AFTER INSTALLNG ONLY BLUE COLOR BACKGROUDN IS RUNING NIOTE ACTUAL SODA

int foo()
{
    // more stuff
    foo();
}

4. export HOST_IP={your_real_host_ip} -----    tRYING TO GET IP ADDRES USING THIS COMMAND

( at java.io.PrintStream.write(PrintStream.java:480)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
        at java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:185)
        at java.io.PrintStream.write(PrintStream.java:527)
        at java.io.PrintStream.print(PrintStream.java:669)
        at java.io.PrintStream.println(PrintStream.java:806)

3. AFTER INSTALLNG ONLY BLUE COLOR BACKGROUDN IS RUNING NIOTE ACTUAL SODA

int foo()
{
    // more stuff
    foo();
}

**Comment by DIVYANUNU** [comment]
@DIVYANUNU YOU GUYS ARWE AWESOME KEEP DOING
